### ISSUE TITLE
Size of file to donwload

### ISSUE THREAD

**Issue by seransaca** [lingochamp/FileDownloader#336] opened 2016-09-29 10:08 UTC
Hello,

I would like to know if there is any way to know the individual or total size of the files to download to put a percentage of the download process.
I know no way of knowing the number of files to download, but also I would like to put the total size of files and each "X" time to update the percentage size of the downloaded so far.

Thank you

EDIT:
The function `BaseDownloadTask.getSmallFileTotalBytes();` returns you the size in bytes of the file in question?

**Comment by Jacksgong** [comment] 2016-09-29 12:13
If you want to know the progress of the individual downloading task, it's very easy: 

- You can get `sofarBytes` and `totalBytes` in callback methods in `FileDownloadListener`.
- You also can get `sofarBytes` and `totalBytes` through `FileDownloader#getSofar` and `FileDownloader#getTotal` by the downloading task identity(id).

---

If you downloading several tasks and you want to know the global progress, please Ref: #256 .

**Comment by seransaca** [comment] 2016-09-29 17:15
Okay, I've seen the way to get power, but I encuenta with a new problem and I never enters the method 
FileDownloadListener#progress. How do I get into this method?

**Comment by Jacksgong** [comment] 2016-09-30 02:50
There are several things can affect the frequency of `FileDownloadListener#progress` callback:

1. [BaseDownloadTask#setCallbackProgressTimes(callbackProgressCount:int)](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/BaseDownloadTask.java#L72)、[BaseDownloadTask#setCallbackProgressMinInterval(minIntervalMillis:int)](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/BaseDownloadTask.java#L91)、[BaseDownloadTask#setCallbackProgressIgnored()](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/BaseDownloadTask.java#L107)
2. The length of data to fetch, we [fetch data from the input stream](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L418) through a [4096 buffer byte array](https://github.com/lingochamp/FileDownloader/blob/master/library/src/main/java/com/liulishuo/filedownloader/services/FileDownloadRunnable.java#L427) each step, if the of data to fetch is less than 4096 byte, you maybe only can receive the progress callback once.
3. If the resource is chunked( The `Transfer-Encoding` in the header of response is `chunked`), the value is set by `BaseDownloadTask#setCallbackProgressTimes` will be invalid, because we can't get the length of resource before finish downloading,  but the value set by `BaseDownloadTask#setCallbackProgressMinInterval` is still work, so the callback of progress will be trigger after fetch each chunk of resource and filter by `ProgressMinInterval`.

**Comment by seransaca** [comment] 2016-09-30 08:20
Sorry but I try this:
`new FileDownloadQueueSet(mDownloadListener)
                .setCallbackProgressMinInterval(1000)
                .setAutoRetryTimes(RETRY_TIMES)
                .downloadTogether(downloadTasks)
                .start();`

and this:
`downloadTasks.add(FileDownloader.getImpl()
                            .create(offer.getUrl())
                            .setPath(offer.getLocalPath())
                            .setTag(offer.getId())
                            .setCallbackProgressMinInterval(1000)
            );`

and in any case I managed to activate the method progress()

PS: `downloadTask` is a `List<BaseDownloadTask>` and `mDownloadListener` is a `FileDownloadListener()`

**Comment by Jacksgong** [comment] 2016-09-30 14:18
I test the progress method callback works well in the demo project. Is there a problem which is no `progress` method callback only in some special URLs? Can you test your URLs in the demo project or provide your URLs, I will check out the cause for you.

---

PS: `setCallbackProgressMinInterval(1000)` means the interval of  `progress` method callback must more than 1 second.

**Closed** 2016-12-09 15:02 UTC
Labels: question
