### ISSUE TITLE
losing data after Retry and pause  

### ISSUE THREAD

**Issue by Jeffin21** [lingochamp/FileDownloader#890] opened 2017-12-26 03:20 UTC
Download a file in very slow network better to catch the bug in 2kb/sec network and the downloader tries to retry the download and press pause then you see the decrease in the download data

log
12-20 14:57:21.477 23929-23929/com.download.gdm V/SRL: task item status:3
12-20 14:57:21.477 23929-23929/com.download.gdm V/SRL: task item status1:3
12-20 14:57:22.481 23929-23929/com.download.gdm V/SRL: task item status:3
12-20 14:57:22.481 23929-23929/com.download.gdm V/SRL: task item status1:3
12-20 14:57:22.983 23929-23929/com.download.gdm V/SRL: notification show : 5
12-20 14:57:22.984 23929-23929/com.download.gdm I/System.out: show notiiify: 330226
12-20 14:57:22.992 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 3.6 KB/s | 9h:42m:41s
12-20 14:57:22.992 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 3.6 KB/s | 9h:42m:41s
12-20 14:57:23.473 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:23.473 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:24.227 28433-28433/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:24.228 28433-28433/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:24.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:24.468 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:25.024 24091-28289/com.download.gdm:filedownloader I/System.out: findContentLength: 18596143
12-20 14:57:25.024 24091-28289/com.download.gdm:filedownloader V/SRL: FileDownloadOutputStream:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:25.029 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.029 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.030 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader I/System.out: File Utile:SDcard==/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.tempFileLocationDetails:SDcard
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader V/SRL: DocFil:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp==true
12-20 14:57:25.037 24091-28289/com.download.gdm:filedownloader I/System.out: File Utile file:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:25.043 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.044 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.044 24091-28289/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:25.473 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:25.473 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:26.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:26.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:27.469 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:27.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:28.469 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:28.469 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:29.255 28435-28435/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:29.256 28435-28435/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:29.468 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:29.468 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:29.599 266-266/? I/SFPerfTracer: triggers: (rate: 102:5714) (compose: 15:650) (post: 0:757) (render: 29:1127) (1:207086 frames) (2:244221)
12-20 14:57:29.599 266-266/? D/SFPerfTracer: layers: (3:9) (FocusedStackFrame (0xb8d355c8): 0:2097)* (DimLayer (0xb8dbaa58): 0:45)* (StatusBar (0xb8d89e20): 0:24160) (com.android.systemui.ImageWallpaper (0xb8db3b38): 0:494)* (DimLayer (0xb8d7f790): 0:114)* (DimLayer (0xb8d9ff48): 0:16)* (NavigationBar (0xb8da90e8): 0:28) (com.download.gdm/com.ggates.android.gdm.residingmenu.MainActivity_Residing_Menu (0xb8d80a58): 2:315)
12-20 14:57:30.486 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:30.486 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:31.486 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:31.486 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:32.484 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:32.484 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:33.483 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:33.483 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:34.282 28436-28436/? E/NEW_BHD: Battery Power Supply logging Daemon start!!!!!
12-20 14:57:34.283 28436-28436/? E/NEW_BHD: Cannot run on production devices!
12-20 14:57:34.482 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:34.482 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:35.218 23929-23929/com.download.gdm V/SRL: notification show : 5
12-20 14:57:35.218 23929-23929/com.download.gdm I/System.out: show notiiify: 403983
12-20 14:57:35.477 23929-23929/com.download.gdm V/SRL: task item status:5
12-20 14:57:35.477 23929-23929/com.download.gdm V/SRL: task item status1:5
12-20 14:57:35.878 24091-28396/com.download.gdm:filedownloader I/System.out: findContentLength: 18566744
12-20 14:57:35.878 24091-28396/com.download.gdm:filedownloader V/SRL: FileDownloadOutputStream:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:35.884 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.885 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.885 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader I/System.out: File Utile:SDcard==/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.tempFileLocationDetails:SDcard
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader V/SRL: DocFil:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp==true
12-20 14:57:35.889 24091-28396/com.download.gdm:filedownloader I/System.out: File Utile file:/storage/3B1F-1B05/music/Watch Kal Ho Naa Ho Online-Free -.mp4.temp
12-20 14:57:35.894 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPath1Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.895 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhh 2222:Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:35.895 24091-28396/com.download.gdm:filedownloader I/System.out: getItemByPathhhhhhN;Watch Kal Ho Naa Ho Online-Free -.mp4
12-20 14:57:36.245 7206-7304/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
12-20 14:57:36.254 23929-23929/com.download.gdm V/SRL: notification show : -2
12-20 14:57:36.254 23929-23929/com.download.gdm I/System.out: show notiiify: 192641
12-20 14:57:36.255 23929-23929/com.download.gdm V/SRL: remainingTimeStr getSpeed: 5.9 KB/s | 5h:58m:41s

**Comment by Jeffin21** [comment] 2018-01-01 07:13
@Jacksgong

**Comment by rantianhua** [comment] 2018-01-01 12:00
Hi, @Jeffin21 
The log you provided is printed by yourself, can you open Filedownloader's log? Just add this code: `FileDownloadLog.NEED_LOG = true` before you start downloading, and then provide the log of Filedownloader. This will help me to analysis the problem. Thanks!

**Comment by Jeffin21** [comment] 2018-01-01 15:29
Try to download file in very slow network , download speed at 3kb/s when the network is gone they downloaded start retrying then this problem happens

**Comment by rantianhua** [comment] 2018-01-02 13:18
Ok, I will reproduce it and then give you a feedback.

**Comment by rantianhua** [comment] 2018-01-14 06:54
This problem is because that the pause action isn't synchronized with the update action of progress, and this bug has been fixed with pull request #900

**Closed by rantianhua** 2018-01-14 06:54 UTC
Labels: need-verify
